import React, { useState } from "react";
import {
  Sparkles, Loader2, AlertTriangle, CheckCircle, FileText,
  Target, BarChart2, Download, RefreshCw, ChevronDown, X, Plus
} from "lucide-react";

interface AtsAuditorProps {
  resumeText: string;
}

interface SkillsData {
  categories: Array<{ name: string; skills: string[] }>;
  totalCount: number;
  hardSkillPct: number;
  quantifiedCount: number;
  quantifiedExamples: string[];
}

interface KeywordData {
  rewrites: Array<{ before: string; after: string; reason: string }>;
}

interface MappingItem {
  resumeSkill: string;
  standardTerm: string;
  status: string;
  priority: string;
}

interface HardSoftSkill {
  skill: string;
  type: string;
  verdict: string;
  strength: string;
}

interface VerbImprovement {
  weak: string;
  strong: string;
  context: string;
}

interface GapItem {
  label: string;
  note: string;
  severity: string;
}

interface RewriteData {
  summary: string;
  skillsSection: string;
  certificationsSection: string;
  changeLog: string[];
}

interface AuditResults {
  skills: SkillsData;
  keywords: KeywordData;
  anzsco: { mappings: MappingItem[] };
  hardSoft: { skills: HardSoftSkill[] };
  verbs: { improvements: VerbImprovement[] };
  gaps: { gaps: GapItem[] };
  rewrite: RewriteData;
}

type StepId = "idle" | "extracting" | "keywords" | "anzsco" | "hardsoft" | "verbs" | "gaps" | "rewrite" | "done";

const STEP_LABELS: Record<StepId, string> = {
  idle: "Ready",
  extracting: "Extracting skills from resume...",
  keywords: "Running keyword phrasing audit...",
  anzsco: "Mapping against ANZSCO / SEEK taxonomy...",
  hardsoft: "Auditing hard vs soft skill balance...",
  verbs: "Auditing action verbs and metrics...",
  gaps: "Running market gap analysis...",
  rewrite: "Generating rewritten resume sections...",
  done: "Done.",
};

const STEP_ORDER: StepId[] = ["extracting", "keywords", "anzsco", "hardsoft", "verbs", "gaps", "rewrite"];

export default function AtsAuditor({ resumeText }: AtsAuditorProps) {
  const [currentStep, setCurrentStep] = useState<StepId>("idle");
  const [results, setResults] = useState<AuditResults | null>(null);
  const [error, setError] = useState("");
  const [openPanels, setOpenPanels] = useState<Record<string, boolean>>({
    skills: true,
    keywords: true,
    anzsco: false,
    hardsoft: false,
    verbs: false,
    gaps: false,
  });

  const togglePanel = (id: string) => {
    setOpenPanels((prev) => ({ ...prev, [id]: !prev[id] }));
  };

  const progressPct = (() => {
    if (currentStep === "idle") return 0;
    if (currentStep === "done") return 100;
    const idx = STEP_ORDER.indexOf(currentStep as any);
    return Math.round((idx / STEP_ORDER.length) * 100);
  })();

  const runAudit = async () => {
    if (resumeText.length < 100) {
      setError("Resume text is too short. Fill in more content first.");
      return;
    }
    setError("");
    setResults(null);
    setCurrentStep("extracting");

    try {
      let stepIdx = 0;
      for (const step of STEP_ORDER) {
        setCurrentStep(step);
        await new Promise((r) => setTimeout(r, 300));
        stepIdx++;
      }

      const response = await fetch("/api/ats/audit", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ resumeText }),
      });
      const data = await response.json();
      if (!response.ok) throw new Error(data.error || "Audit failed");
      setResults(data);
      setCurrentStep("done");
    } catch (err: any) {
      setError(err.message || "An error occurred during the audit");
      setCurrentStep("idle");
    }
  };

  const getPlainText = () => {
    if (!results) return "";
    const rw = results.rewrite;
    return [
      "PROFESSIONAL SUMMARY",
      "=".repeat(50),
      rw.summary,
      "",
      "SKILLS & TOOLS",
      "=".repeat(50),
      rw.skillsSection,
      "",
      "LICENCES & CERTIFICATIONS",
      "=".repeat(50),
      rw.certificationsSection,
      "",
      "WHAT CHANGED & WHY",
      "=".repeat(50),
      ...rw.changeLog.map((c, i) => `${i + 1}. ${c}`),
      "",
      "---",
      "Generated by Portfolio Studio ATS Auditor",
    ].join("\n");
  };

  const downloadTXT = () => {
    const blob = new Blob([getPlainText()], { type: "text/plain" });
    const a = document.createElement("a");
    a.href = URL.createObjectURL(blob);
    a.download = "resume-rewritten-sections.txt";
    a.click();
  };

  const statusBadge = (s: string) => {
    if (s === "strong match") return <span className="badge badge-green">strong match</span>;
    if (s === "partial match") return <span className="badge badge-amber">partial match</span>;
    return <span className="badge badge-red">missing</span>;
  };

  const prioBadge = (p: string) => {
    if (p === "high") return <span className="badge badge-red">high</span>;
    if (p === "medium") return <span className="badge badge-amber">medium</span>;
    return <span className="badge badge-gray">low</span>;
  };

  const typeBadge = (t: string) =>
    t === "hard"
      ? <span className="badge badge-green">hard</span>
      : <span className="badge badge-amber">soft</span>;

  const strengthColor = (s: string) =>
    s === "strong" ? "#3dd68c" : s === "moderate" ? "#f0a04a" : "#f06060";

  const PanelToggle = ({ id, label, count }: { id: string; label: string; count?: number }) => (
    <div
      role="button"
      tabIndex={0}
      onClick={() => togglePanel(id)}
      onKeyDown={(e) => { if (e.key === "Enter" || e.key === " ") togglePanel(id); }}
      className="flex items-center justify-between px-3 py-2.5 bg-slate-100 dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-xl cursor-pointer hover:bg-slate-200/70 dark:hover:bg-slate-800/70 transition-colors"
    >
      <span className="text-[11px] font-bold text-slate-700 dark:text-slate-300 uppercase tracking-wider">
        {label}{count !== undefined ? ` (${count})` : ""}
      </span>
      <ChevronDown className={`w-3.5 h-3.5 text-slate-400 transition-transform ${openPanels[id] ? "rotate-180" : ""}`} />
    </div>
  );

  if (currentStep !== "idle" && !results && !error) {
    return (
      <div className="space-y-4">
        <div className="bg-slate-50 dark:bg-slate-900/40 border border-slate-200 dark:border-slate-800 rounded-xl p-4 text-center">
          <div className="text-3xl mb-3">⚙️</div>
          <div className="text-sm font-semibold text-slate-800 dark:text-slate-100 mb-3">Analysing your resume</div>
          <div className="h-1.5 bg-slate-200 dark:bg-slate-800 rounded-full overflow-hidden mb-2">
            <div
              className="h-full bg-gradient-to-r from-sky-500 to-violet-500 rounded-full transition-all duration-500 ease-out"
              style={{ width: `${progressPct}%` }}
            />
          </div>
          <div className="text-[11px] text-slate-500">{STEP_LABELS[currentStep]}</div>
        </div>
      </div>
    );
  }

  return (
    <div className="space-y-4">
      {/* Error banner */}
      {error && (
        <div className="flex items-start gap-2 p-3 bg-rose-500/10 border border-rose-500/20 text-rose-600 dark:text-rose-400 rounded-xl text-[11px]">
          <AlertTriangle className="w-4 h-4 shrink-0 mt-0.5" />
          <span>{error}</span>
          <button type="button" onClick={() => setError("")} className="ml-auto shrink-0 cursor-pointer">
            <X className="w-3.5 h-3.5" />
          </button>
        </div>
      )}

      {/* Run button */}
      <button
        type="button"
        onClick={runAudit}
        disabled={currentStep !== "idle" || resumeText.length < 100}
        className="w-full py-2.5 bg-gradient-to-r from-sky-600 to-violet-600 hover:from-sky-500 hover:to-violet-500 disabled:from-slate-300 disabled:to-slate-300 dark:disabled:from-slate-800 dark:disabled:to-slate-800 text-white disabled:text-slate-400 rounded-xl text-xs font-bold tracking-wider flex items-center justify-center gap-2 transition-all cursor-pointer shadow-md"
      >
        <Sparkles className="w-4 h-4" />
        {resumeText.length < 100 ? "Add more resume content first" : "Run Full ATS Audit"}
      </button>

      {!results && !error && currentStep === "idle" && (
        <p className="text-[10px] text-slate-400 text-center leading-relaxed">
          Analyses your resume across 7 lenses — skill extraction, keyword phrasing, ANZSCO taxonomy, hard/soft balance, action verb audit, market gap analysis, and full rewrite.
        </p>
      )}

      {/* Results */}
      {results && (
        <>
          {/* Metrics row */}
          <div className="grid grid-cols-2 gap-2">
            <div className="bg-slate-100 dark:bg-slate-900/60 border border-slate-200 dark:border-slate-800 rounded-xl p-3">
              <div className="text-[9px] text-slate-500 uppercase tracking-wider mb-1">Skills</div>
              <div className="text-xl font-bold text-slate-800 dark:text-slate-100">{results.skills.totalCount}</div>
              <div className="text-[9px] text-slate-400">{results.skills.categories.length} categories</div>
            </div>
            <div className="bg-slate-100 dark:bg-slate-900/60 border border-slate-200 dark:border-slate-800 rounded-xl p-3">
              <div className="text-[9px] text-slate-500 uppercase tracking-wider mb-1">Hard skill ratio</div>
              <div className="text-xl font-bold text-slate-800 dark:text-slate-100">{results.skills.hardSkillPct}%</div>
              <div className="text-[9px] text-slate-400">ATS-weighted</div>
            </div>
            <div className="bg-slate-100 dark:bg-slate-900/60 border border-slate-200 dark:border-slate-800 rounded-xl p-3">
              <div className="text-[9px] text-slate-500 uppercase tracking-wider mb-1">Quantified</div>
              <div className="text-xl font-bold text-slate-800 dark:text-slate-100">{results.skills.quantifiedCount}</div>
              <div className="text-[9px] text-slate-400">{results.skills.quantifiedExamples[0] || ""}</div>
            </div>
            <div className="bg-slate-100 dark:bg-slate-900/60 border border-slate-200 dark:border-slate-800 rounded-xl p-3">
              <div className="text-[9px] text-slate-500 uppercase tracking-wider mb-1">High-priority gaps</div>
              <div className="text-xl font-bold text-slate-800 dark:text-slate-100">
                {results.gaps.gaps.filter((g) => g.severity === "high").length}
              </div>
              <div className="text-[9px] text-slate-400">needs attention</div>
            </div>
          </div>

          {/* Panel: Skill extraction */}
          <div className="space-y-1">
            <PanelToggle id="skills" label="Skill extraction" count={results.skills.totalCount} />
            {openPanels.skills && (
              <div className="p-3 bg-white dark:bg-slate-950/30 border border-slate-200 dark:border-slate-800 rounded-xl space-y-3 text-[11px]">
                <div className="flex flex-wrap gap-1">
                  {results.skills.categories.map((cat) =>
                    cat.skills.map((s, i) => (
                      <span
                        key={`${cat.name}-${i}`}
                        className="px-2 py-0.5 bg-slate-100 dark:bg-slate-900 border border-slate-200 dark:border-slate-700 rounded-full text-[10px] text-slate-700 dark:text-slate-300"
                      >
                        {s}
                      </span>
                    ))
                  )}
                </div>
                {results.skills.categories.map((cat) => (
                  <div key={cat.name}>
                    <div className="text-[9px] font-bold text-slate-500 uppercase tracking-wider mb-1">{cat.name}</div>
                    <div className="flex flex-wrap gap-1">
                      {cat.skills.map((s, i) => (
                        <span
                          key={i}
                          className="px-2 py-0.5 bg-sky-50 dark:bg-sky-950/30 border border-sky-200 dark:border-sky-800 rounded-full text-[10px] text-sky-700 dark:text-sky-300"
                        >
                          {s}
                        </span>
                      ))}
                    </div>
                  </div>
                ))}
              </div>
            )}
          </div>

          {/* Panel: Keyword phrasing */}
          <div className="space-y-1">
            <PanelToggle id="keywords" label="Keyword phrasing audit" count={results.keywords.rewrites.length} />
            {openPanels.keywords && (
              <div className="p-3 bg-white dark:bg-slate-950/30 border border-slate-200 dark:border-slate-800 rounded-xl space-y-2 text-[11px]">
                {results.keywords.rewrites.map((r, i) => (
                  <div key={i} className="flex gap-2 items-start p-2 bg-slate-50 dark:bg-slate-900/60 rounded-lg border border-slate-100 dark:border-slate-800">
                    <span className="text-slate-400 shrink-0 mt-0.5">→</span>
                    <div>
                      <div className="text-[10px] text-slate-400 line-through">{r.before}</div>
                      <div className="text-xs text-sky-600 dark:text-sky-400 font-medium">{r.after}</div>
                      <div className="text-[9px] text-slate-400 mt-0.5">{r.reason}</div>
                    </div>
                  </div>
                ))}
              </div>
            )}
          </div>

          {/* Panel: ANZSCO */}
          <div className="space-y-1">
            <PanelToggle id="anzsco" label="ANZSCO / SEEK taxonomy" count={results.anzsco.mappings.length} />
            {openPanels.anzsco && (
              <div className="p-3 bg-white dark:bg-slate-950/30 border border-slate-200 dark:border-slate-800 rounded-xl overflow-x-auto">
                <table className="w-full text-[10px] border-collapse">
                  <thead>
                    <tr className="text-[9px] text-slate-500 uppercase tracking-wider border-b border-slate-200 dark:border-slate-700">
                      <th className="text-left py-1.5 pr-2">Your skill</th>
                      <th className="text-left py-1.5 pr-2">SEEK standard</th>
                      <th className="text-left py-1.5 pr-2">Match</th>
                      <th className="text-left py-1.5">Priority</th>
                    </tr>
                  </thead>
                  <tbody>
                    {results.anzsco.mappings.map((m, i) => (
                      <tr key={i} className="border-b border-slate-100 dark:border-slate-800/50">
                        <td className="py-1.5 pr-2 text-slate-700 dark:text-slate-300">{m.resumeSkill}</td>
                        <td className="py-1.5 pr-2 text-slate-500">{m.standardTerm}</td>
                        <td className="py-1.5 pr-2">{statusBadge(m.status)}</td>
                        <td className="py-1.5">{prioBadge(m.priority)}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            )}
          </div>

          {/* Panel: Hard vs Soft */}
          <div className="space-y-1">
            <PanelToggle id="hardsoft" label="Hard vs soft balance" count={results.hardSoft.skills.length} />
            {openPanels.hardsoft && (
              <div className="p-3 bg-white dark:bg-slate-950/30 border border-slate-200 dark:border-slate-800 rounded-xl space-y-1 text-[11px]">
                {results.hardSoft.skills.map((sk, i) => {
                  const pct = sk.strength === "strong" ? 90 : sk.strength === "moderate" ? 55 : 25;
                  return (
                    <div key={i} className="flex items-center gap-2 py-1.5 border-b border-slate-100 dark:border-slate-800/50 last:border-0">
                      <span className="w-20 text-slate-700 dark:text-slate-300 text-[10px]">{sk.skill}</span>
                      <span className="w-14">{typeBadge(sk.type)}</span>
                      <div className="flex-1">
                        <div className="flex items-center gap-2">
                          <div className="flex-1 h-1.5 bg-slate-200 dark:bg-slate-800 rounded-full overflow-hidden">
                            <div className="h-full rounded-full transition-all" style={{ width: `${pct}%`, backgroundColor: strengthColor(sk.strength) }} />
                          </div>
                          <span className="text-[9px]" style={{ color: strengthColor(sk.strength) }}>{sk.strength}</span>
                        </div>
                        <div className="text-[9px] text-slate-400 mt-0.5">{sk.verdict}</div>
                      </div>
                    </div>
                  );
                })}
              </div>
            )}
          </div>

          {/* Panel: Action verbs */}
          <div className="space-y-1">
            <PanelToggle id="verbs" label="Action verb & metric audit" count={results.verbs.improvements.length} />
            {openPanels.verbs && (
              <div className="grid grid-cols-2 gap-2">
                {results.verbs.improvements.map((v, i) => (
                  <div key={i} className="p-2.5 bg-white dark:bg-slate-950/30 border border-slate-200 dark:border-slate-800 rounded-xl">
                    <div className="text-[10px] text-slate-400 line-through mb-1">{v.weak}</div>
                    <div className="text-xs text-slate-800 dark:text-slate-100 font-medium">{v.strong}</div>
                    <div className="text-[9px] text-slate-400 mt-1">{v.context}</div>
                  </div>
                ))}
              </div>
            )}
          </div>

          {/* Panel: Gaps */}
          <div className="space-y-1">
            <PanelToggle id="gaps" label="Market gap analysis" count={results.gaps.gaps.length} />
            {openPanels.gaps && (
              <div className="p-3 bg-white dark:bg-slate-950/30 border border-slate-200 dark:border-slate-800 rounded-xl space-y-2 text-[11px]">
                {results.gaps.gaps.map((g, i) => {
                  const dot = g.severity === "high" ? "bg-red-500" : g.severity === "medium" ? "bg-amber-500" : "bg-green-500";
                  return (
                    <div key={i} className="flex gap-2 items-start">
                      <div className={`w-2 h-2 rounded-full shrink-0 mt-1 ${dot}`} />
                      <div>
                        <div className="font-semibold text-slate-700 dark:text-slate-300">{g.label}</div>
                        <div className="text-[10px] text-slate-400">{g.note}</div>
                      </div>
                    </div>
                  );
                })}
              </div>
            )}
          </div>

          {/* Rewrite output */}
          <div className="bg-white dark:bg-slate-950/30 border border-slate-200 dark:border-slate-800 rounded-xl p-[18px] space-y-3">
            <div className="flex items-center justify-between">
              <h3 className="text-[11px] font-bold text-slate-800 dark:text-slate-100 uppercase tracking-wider">
                Rewritten Resume Sections
              </h3>
              <div className="flex gap-2">
                <button type="button" onClick={downloadTXT} className="flex items-center gap-1 px-2.5 py-1 bg-slate-800 dark:bg-slate-100 text-white dark:text-slate-900 rounded-lg text-[9px] font-bold cursor-pointer hover:opacity-90 transition-opacity">
                  <Download className="w-3 h-3" />
                  .txt
                </button>
              </div>
            </div>

            <div>
              <div className="text-[9px] font-bold text-sky-600 dark:text-sky-400 uppercase tracking-wider mb-1">Professional Summary</div>
              <div className="bg-slate-50 dark:bg-slate-900/60 border border-slate-200 dark:border-slate-800 rounded-lg p-3 text-[11px] text-slate-700 dark:text-slate-300 whitespace-pre-wrap leading-relaxed">
                {results.rewrite.summary}
              </div>
            </div>

            <div>
              <div className="text-[9px] font-bold text-sky-600 dark:text-sky-400 uppercase tracking-wider mb-1">Skills &amp; Tools</div>
              <div className="bg-slate-50 dark:bg-slate-900/60 border border-slate-200 dark:border-slate-800 rounded-lg p-3 text-[11px] text-slate-700 dark:text-slate-300 whitespace-pre-wrap font-mono leading-relaxed">
                {results.rewrite.skillsSection}
              </div>
            </div>

            <div>
              <div className="text-[9px] font-bold text-sky-600 dark:text-sky-400 uppercase tracking-wider mb-1">Licences &amp; Certifications</div>
              <div className="bg-slate-50 dark:bg-slate-900/60 border border-slate-200 dark:border-slate-800 rounded-lg p-3 text-[11px] text-slate-700 dark:text-slate-300 whitespace-pre-wrap font-mono leading-relaxed">
                {results.rewrite.certificationsSection}
              </div>
            </div>

            <div>
              <div className="text-[9px] font-bold text-sky-600 dark:text-sky-400 uppercase tracking-wider mb-1">What changed &amp; why</div>
              <div className="space-y-1">
                {results.rewrite.changeLog.map((c, i) => (
                  <div key={i} className="flex gap-2 items-start p-2 bg-slate-50 dark:bg-slate-900/40 rounded-lg text-[10px] text-slate-600 dark:text-slate-400">
                    <span className="text-sky-600 dark:text-sky-400 font-bold shrink-0">{i + 1}.</span>
                    <span>{c}</span>
                  </div>
                ))}
              </div>
            </div>
          </div>

          {/* Rerun */}
          <button
            type="button"
            onClick={runAudit}
            className="w-full py-2 bg-slate-200 dark:bg-slate-800 hover:bg-slate-300 dark:hover:bg-slate-700 rounded-xl text-[10px] font-bold text-slate-600 dark:text-slate-300 flex items-center justify-center gap-2 transition-colors cursor-pointer"
          >
            <RefreshCw className="w-3.5 h-3.5" />
            Run Audit Again
          </button>
        </>
      )}
    </div>
  );
}
